title: IQDevs Blog
email: ceo@skaykeapp.com
description: > # this means to ignore newlines until "baseurl:"
  IQDevs is a group on Facebook full of people with technical skills in different fields in technology (though the vast majourity comes from a backgroup in computer science and software engineering, but that's certainly not the limit).
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  iqdevs

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
